### ISSUE TITLE
How to run TYY_demo.py

### ISSUE THREAD

**Issue by wwwwwinz** [shamangary/Keras-real-time-age-gender-estimation-demo#1]
Hello I've tried the demo.py but failed with error“OSError: [WinError 6] The handle is invalid” in VideoFileClip function
I also tried the command `KERAS_BACKEND=tensorflow CUDA_VISIBLE_DEVICES='3' python TYY_demo.py MV2.mp4` also failed too for SyntaxError...

**Comment by 3073** [comment]
Hi bro ....... i need to use  https://github.com/nanfengpo/age-gender-estimation for age estimation..... but your seem very short... and confuses me with the one in the link.  what is the extra line of code in the wide_resnet.py in the link when compared to your in TYY_model.py... 
in Class TYY_2stream or TYY_1 stream, there is only one function called def _call_().  thank you ..

**Comment by shamangary** [comment]
As I point out at the first line of the readme file, the main part of the project has moved to 
https://github.com/shamangary/SSR-Net
Please check that out.

**Comment by 3073** [comment]
Thank you  i have seen it ... what if i use this for this time because i need it to be short?
